name: Folder Creator

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run folder creator
        run: python folderCreater.py

      - name: Commit created folder (if any)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Auto-create folder(s)"
          git push
